wandb_version: 1

batch_size:
  value: 32
bidirectional:
  value: true
cell_type:
  value: RNN
dec_dropout:
  value: 0.3
decoder_layers:
  value: 5
embedding_dim:
  value: 64
enc_dropout:
  value: 0
encoder_layers:
  value: 3
epochs:
  value: 20
hidden_size:
  value: 512
learning_rate:
  value: 0.001
