wandb_version: 1

batch_size:
  value: 256
bidirectional:
  value: true
cell_type:
  value: GRU
dec_dropout:
  value: 0.4
decoder_layers:
  value: 3
embedding_dim:
  value: 32
enc_dropout:
  value: 0.1
encoder_layers:
  value: 5
epochs:
  value: 20
hidden_size:
  value: 256
learning_rate:
  value: 0.001
