wandb_version: 1

batch_size:
  value: 64
bidirectional:
  value: true
cell_type:
  value: LSTM
dec_dropout:
  value: 0
decoder_layers:
  value: 4
embedding_dim:
  value: 64
enc_dropout:
  value: 0
encoder_layers:
  value: 3
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.001
