wandb_version: 1

batch_size:
  value: 256
bidirectional:
  value: true
cell_type:
  value: GRU
dec_dropout:
  value: 0.3
decoder_layers:
  value: 4
embedding_dim:
  value: 16
enc_dropout:
  value: 0.3
encoder_layers:
  value: 3
epochs:
  value: 30
hidden_size:
  value: 256
learning_rate:
  value: 0.001
