wandb_version: 1

batch_size:
  value: 32
bidirectional:
  value: true
cell_type:
  value: GRU
dec_dropout:
  value: 0.2
decoder_layers:
  value: 3
embedding_dim:
  value: 16
enc_dropout:
  value: 0.2
encoder_layers:
  value: 4
epochs:
  value: 10
hidden_size:
  value: 16
learning_rate:
  value: 0.1
