wandb_version: 1

batch_size:
  value: 64
bidirectional:
  value: false
cell_type:
  value: RNN
dec_dropout:
  value: 0
decoder_layers:
  value: 5
embedding_dim:
  value: 512
enc_dropout:
  value: 0.2
encoder_layers:
  value: 4
epochs:
  value: 30
hidden_size:
  value: 16
learning_rate:
  value: 0.001
