wandb_version: 1

batch_size:
  value: 256
bidirectional:
  value: false
cell_type:
  value: RNN
dec_dropout:
  value: 0
decoder_layers:
  value: 3
embedding_dim:
  value: 256
enc_dropout:
  value: 0.3
encoder_layers:
  value: 5
epochs:
  value: 30
hidden_size:
  value: 32
learning_rate:
  value: 0.001
