wandb_version: 1

batch_size:
  value: 64
bidirectional:
  value: false
cell_type:
  value: LSTM
dec_dropout:
  value: 0.1
decoder_layers:
  value: 5
embedding_dim:
  value: 128
enc_dropout:
  value: 0.1
encoder_layers:
  value: 5
epochs:
  value: 10
hidden_size:
  value: 16
learning_rate:
  value: 0.1
