wandb_version: 1

batch_size:
  value: 32
bidirectional:
  value: false
cell_type:
  value: LSTM
dec_dropout:
  value: 0.3
decoder_layers:
  value: 5
embedding_dim:
  value: 512
enc_dropout:
  value: 0.4
encoder_layers:
  value: 4
epochs:
  value: 30
hidden_size:
  value: 32
learning_rate:
  value: 0.1
