wandb_version: 1

batch_size:
  value: 64
bidirectional:
  value: true
cell_type:
  value: LSTM
dec_dropout:
  value: 0.2
decoder_layers:
  value: 3
embedding_dim:
  value: 128
enc_dropout:
  value: 0.3
encoder_layers:
  value: 3
epochs:
  value: 30
hidden_size:
  value: 64
learning_rate:
  value: 0.001
