wandb_version: 1

batch_size:
  value: 128
bidirectional:
  value: true
cell_type:
  value: RNN
dec_dropout:
  value: 0.2
decoder_layers:
  value: 5
embedding_dim:
  value: 32
enc_dropout:
  value: 0.2
encoder_layers:
  value: 3
epochs:
  value: 30
hidden_size:
  value: 16
learning_rate:
  value: 0.01
