wandb_version: 1

batch_size:
  value: 32
bidirectional:
  value: false
cell_type:
  value: GRU
dec_dropout:
  value: 0
decoder_layers:
  value: 4
embedding_dim:
  value: 16
enc_dropout:
  value: 0
encoder_layers:
  value: 3
epochs:
  value: 20
hidden_size:
  value: 32
learning_rate:
  value: 0.001
