wandb_version: 1

batch_size:
  value: 128
bidirectional:
  value: false
cell_type:
  value: GRU
dec_dropout:
  value: 0.1
decoder_layers:
  value: 4
embedding_dim:
  value: 512
enc_dropout:
  value: 0.1
encoder_layers:
  value: 4
epochs:
  value: 20
hidden_size:
  value: 128
learning_rate:
  value: 0.1
