wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714360948.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.5
      5: 0.16.4
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
batch_size:
  desc: null
  value: 64
bidirectional:
  desc: null
  value: false
cell_type:
  desc: null
  value: RNN
dec_dropout:
  desc: null
  value: 0
decoder_layers:
  desc: null
  value: 5
embedding_dim:
  desc: null
  value: 16
enc_dropout:
  desc: null
  value: 0.3
encoder_layers:
  desc: null
  value: 4
epochs:
  desc: null
  value: 30
hidden_size:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.001
